export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_START =  'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_END';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const INITIALIZE_HOMEPAGE_MOVIES = 'INITIALIZE_HOMEPAGE_MOVIES';

export const GET_SINGLE_MOVIE = 'GET_SINGLE_MOVIE';
export const GET_SINGLE_MOVIE_START = 'GET_SINGLE_MOVIE_START';
export const GET_SINGLE_MOVIE_SUCCESS = 'GET_SINGLE_MOVIE_SUCCESS';
export const GET_SINGLE_MOVIE_ERROR = 'GET_SINGLE_MOVIE_ERROR';


export const GET_SEARCH_START = 'GET_SEARCH_START';
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS';
export const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR';



